services:
  - type: web
    name: teamflowapi
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /health